name: CICD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  check_working_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install scikit-learn joblib

      - name: Train model
        run: python train.py

      - name: Test model
        run: python test.py